version: "3.8"
services:
  api:
    build: ./backend
    # volumes:
    #   - ./backend:/app
    ports:
      - 5000:5000
  web:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000
