export const listFileType = [
  "image/png",
  "image/jpeg",
  "image/jpg",
  "application/pdf",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.rar",
  "text/plain",
  "application/x-7z-compressed",
  "application/zip",
  "audio/mpeg",
  "video/x-ms-wmv",
  "video/mp4",
];
